### PR TITLE
Project: Social Media Website - Milestone 2 (friendship v2)

### PR DESCRIPTION
**Pull request by VanessaAoki**
This is the 7th project of the RoR module.

I created a model with associations and all requests features for friendships.

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done**. 👍🏽 

### Well-done 💯 
    1. The tests run just fine.

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED
> You seem to have missed the requirements for this milestone since you haven't made any of the requested changes. I'll explain to you what exactly the requirements need. I won't use comments since the files that need necessary changes aren't available for use.

- [x] In the User model, once a friendship is confirmed, an additional row with reversed user-friend pair is created using the `confirm_friend(user)` method. Thanks to this, we can find user friends only by user_id in friendships table and can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

- [x] Using the same approach as above and for the same reason, change the `pending_friends` method. `pending_friends` can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

- [x] Now you can guess what's next, 😄 `friend_requests` method.
`friend_requests` can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby). Remember to use 'has_many' & 'through' ':inverted_friendships'

- [x] PostsController index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from Odin Project). Currently, your app shows all posts to users that are not even friends.

- [x] You have the tests mixed up. The unit tests should have tests like validation tests for models, association tests for the models, etc. You have some feature tests in the spec/unit/comment file. Move this to the spec/integration directory.
Also, move the spec/integrations/comment file to the spec/unit directory.


### OPTIONAL

- [x] It is a good practice to have zero logic in the views directory. Create methods in the helpers directory and call the methods in the views directory instead.
Read this [article](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) for a head-start. Another great piece to read is this [article](https://brandonhilkert.com/blog/refactoring-logic-from-a-rails-view/)

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Comment by VanessaAoki** [comment]
@mke2111 I'm sorry, I can't see the inline comments mentioned, can you help?

**Comment by mke2111** [comment]
@VanessaAoki,
I couldn't use the comments to the individual files because you hadn't made any changes to those files in particular. Settle with the above review. Please reach out for more clarifications if you need to.
Best Regards 😄

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
------------
Hello @VanessaAoki Great job working on the required changes :clap: 
However, there is a fix to make :hammer_and_wrench: see it below :eyes: 
-------------

- [x] When I try to run `rails db:migrate` I get this error. 

Screenshot from 2021-05-18 19-07-33
-----------------
Please fix this and send it again for another review :muscle: 
HAPPY CODING !!

**Review by mke2111 — APPROVED** [review]
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey @VanessaAoki 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. The association between tables has been set up as requested. 💯 
    2. The use of SQL queries instead of ruby enumerables to access the dB is also done perfectly. 👍🏽 
    

### **_Room for Improvement_** 🤪 

    1. You can take it a step further and find what the `N+1` problem is and how you can solve it. 
    

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Pull request merged**
